// @module Renders the generated rig-entryexec skill from the registry; its description is how agents discover tools.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { paths } from "./paths";
import type { JSONSchema, Registry, ResolvedCommand } from "./registry";

/**
 * The rig-entryexec skill is generated from the registry on every sync. Harnesses only show an
 * agent a skill's description until it's invoked, so the description itself carries the tool list:
 * that's what lets agents reach for rig tools without being told to.
 */
export const ENTRY_SKILL = "rig-entryexec";
export const RIG_SKILLS = new Set([ENTRY_SKILL, "rig-core"]);

/** Agent Skills spec limit for `description`. */
const DESCRIPTION_MAX = 1024;

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

function usage(cmd: ResolvedCommand): string {
  const props = cmd.schema.properties ?? {};
  const required = new Set(cmd.schema.required ?? []);
  const pos = cmd.positional.map((p) => {
    const label = kebab(p) + (props[p]?.type === "array" ? "..." : "");
    return required.has(p) ? `<${label}>` : `[${label}]`;
  });
  return ["rig", cmd.name, ...pos].join(" ");
}

function flagList(cmd: ResolvedCommand): string {
  const props: Record<string, JSONSchema> = cmd.schema.properties ?? {};
  const required = new Set(cmd.schema.required ?? []);
  return Object.entries(props)
    .filter(([k]) => !cmd.positional.includes(k))
    .map(([k, p]) => `\`--${kebab(k)}\`${required.has(k) ? " (required)" : ""}${p.description ? `: ${p.description}` : ""}`)
    .join("; ");
}

export function renderDescription(reg: Registry): string {
  const tools = reg.tools.filter((t) => !t.disabled && t.commands.some((c) => reg.commands.get(c.name) === c));
  const lead =
    "Use proactively, without being asked, whenever a task could be done with the user's `rig` CLI tools; " +
    "prefer them over ad-hoc scripts, raw API calls, or manual checks. ";
  if (!tools.length) return lead + "No tools are installed yet.";

  const full = tools.map((t) => `${t.commands.map((c) => c.name).join(", ")} (${t.description})`);
  const short = tools.map((t) => t.commands.map((c) => c.name).join(", "));
  for (const parts of [full, short]) {
    const desc = `${lead}Available: ${parts.join("; ")}.`;
    if (desc.length <= DESCRIPTION_MAX) return desc;
  }
  const tail = " Run `rig ls` for the full list.";
  return (lead + "Available: " + short.join("; ")).slice(0, DESCRIPTION_MAX - tail.length - 1) + "…" + tail;
}

export function renderEntrySkill(reg: Registry): string {
  const lines = [
    "---",
    `name: ${ENTRY_SKILL}`,
    `description: ${JSON.stringify(renderDescription(reg))}`,
    "---",
    "",
    "<!-- Generated by `rig sync` from tools/. Do not edit: changes are overwritten. -->",
    "",
    "# rig tools",
    "",
    "The user has a personal CLI, `rig`, on PATH. The commands below are theirs. Use them whenever they fit the task,",
    "even if the user didn't mention rig, instead of writing one-off scripts or calling the underlying APIs yourself.",
    "",
  ];

  const tools = reg.tools.filter((t) => !t.disabled);
  if (!tools.length) lines.push("No tools are installed yet.", "");
  for (const tool of tools) {
    const commands = tool.commands.filter((c) => reg.commands.get(c.name) === c);
    if (!commands.length) continue;
    lines.push(`## ${tool.name}`, "", tool.description, "");
    for (const cmd of commands) {
      lines.push(`- \`${usage(cmd)}\`: ${cmd.description}`);
      const flags = flagList(cmd);
      if (flags) lines.push(`  - Flags: ${flags}`);
    }
    if (tool.auth.length) lines.push(`- Needs credentials (${tool.auth.filter((v) => !v.optional).map((v) => v.name).join(", ")}).`);
    lines.push("");
  }

  const related = reg.skills.filter((s) => !s.disabled && !RIG_SKILLS.has(s.name));
  if (related.length) {
    lines.push("## Related skills", "", "rig also syncs these skills. Invoke them when their task comes up:", "");
    for (const s of related) lines.push(`- \`${s.name}\`: ${s.description ?? ""}`);
    lines.push("");
  }

  lines.push(
    "## Calling convention",
    "",
    "- `rig ls` lists commands; `rig <command> --help` shows flags. Check `--help` before the first call.",
    "- Flags are kebab-case. Booleans are bare `--flag` / `--no-flag`. Array flags repeat or take trailing positionals. Complex input: `--input '<json>'`.",
    "- `--json` returns `{\"ok\":true,\"data\":…}` or `{\"ok\":false,\"error\":{\"code\",\"message\",\"hint\"}}`.",
    "- Exit codes: `0` ok, `1` tool/upstream error, `2` bad arguments, `3` credentials missing or rejected.",
    "- On exit `3`, ask the user to run `rig auth <tool>` in their terminal (it's interactive). Never ask for secrets in chat, and never read `~/.config/rig/.env`.",
    "",
    "To add, change, or refactor rig tools and skills, use the `rig-core` skill.",
    "",
  );
  return lines.join("\n");
}

/** Write the generated skill if it changed. Returns whether it was (or would be) written. */
export function writeEntrySkill(reg: Registry, { dryRun = false } = {}): boolean {
  const dir = join(paths.skills, ENTRY_SKILL);
  const file = join(dir, "SKILL.md");
  const content = renderEntrySkill(reg);
  if (existsSync(file) && readFileSync(file, "utf8") === content) return false;
  if (!dryRun) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, content);
  }
  return true;
}
